# Computación Científica Actuarial — Clase 2 Parte 1
**Introducción a Python: entorno, variables, tipos y estructuras básicas**


---
## 9) Clases, atributos y métodos (POO)

La **Programación Orientada a Objetos (POO)** organiza el código en **clases** (moldes) y **objetos** (instancias).
- **Atributos**: datos que describen al objeto (estado).
- **Métodos**: funciones definidas dentro de la clase que describen comportamientos.

`__init__` es el **constructor**: se ejecuta al crear el objeto y sirve para inicializar atributos.

In [13]:
class Auto:
    flota_total = 0  # atributo de clase (compartido)

    def __init__(self, color, marca, anio):
        self.color = color     # atributo de instancia
        self.marca = marca     # atributo de instancia
        self.anio = anio       # atributo de instancia
        Auto.flota_total += 1

    def descripcion(self):     # método de instancia
        return f"{self.marca} {self.color} ({self.anio})"

    def arrancar(self):
        return f"{self.descripcion()} está arrancando"

    @classmethod
    def cantidad_en_flota(cls):
        return cls.flota_total

    @staticmethod
    def es_antiguo(anio):
        return anio < 2000

mi_auto = Auto("rojo", "Toyota", 2020)
otro_auto = Auto("azul", "Ford", 2015)

mi_auto.arrancar(), Auto.cantidad_en_flota(), Auto.es_antiguo(1999)
mi_auto.descripcion()


'Toyota rojo (2020)'

**Notas**:
- `atributo de clase`: pertenece a la clase y lo comparten todas las instancias.
- `atributo de instancia`: propio de cada objeto.
- `@classmethod`: método que recibe `cls` (la clase) en vez de `self`.
- `@staticmethod`: método utilitario que no depende de `self` ni `cls`.

### Mini‑ejercicio 9
- Creá una clase `Poliza` con atributos `asegurado`, `edad`, `prima`.
- Agregá un método `resumen()` que devuelva un string con los datos.
- Probalo creando dos instancias.

In [2]:
# Tu solución acá

class Poliza:
    def __init__(self, asegurado, edad, prima):
        self.asegurado = asegurado
        self.edad = edad
        self.prima = prima
    def resumen(self):
        return f"Poliza de {self.asegurado} | edad={self.edad} | prima={self.prima}"

p1 = Poliza("Juan", 45, 1500)
p2 = Poliza("Ana", 38, 1200)

p1.resumen(), p2.resumen()

('Poliza de Juan | edad=45 | prima=1500',
 'Poliza de Ana | edad=38 | prima=1200')

---
## 10) NumPy: arrays y operaciones vectorizadas

**NumPy** provee `ndarray`, una estructura eficiente para computación numérica vectorizada.

**Creación básica:**

In [20]:
import numpy as np

arr = np.array([10, 20, 30, 40])
mat = np.array([[1,2,3],[4,5,6]])
arr, mat, arr.dtype, arr.shape, mat.shape

type(arr)
arr.dtype
arr.shape
mat.shape


(2, 3)

**Operaciones vectorizadas y estadísticas rápidas:**

In [4]:
arr + 5, arr * 2, arr ** 2, arr.mean(), arr.sum(), arr.min(), arr.max(), arr.std()

(array([15, 25, 35, 45]),
 array([20, 40, 60, 80]),
 array([ 100,  400,  900, 1600]),
 np.float64(25.0),
 np.int64(100),
 np.int64(10),
 np.int64(40),
 np.float64(11.180339887498949))

**Creación útil:** `arange`, `linspace`, ceros/unos aleatorios

In [5]:
np.arange(0, 10, 2), np.linspace(0, 1, 5), np.zeros((2,3)), np.ones((2,3)), np.random.rand(2,3)

(array([0, 2, 4, 6, 8]),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]),
 array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[0.43040449, 0.48144661, 0.06671472],
        [0.22644472, 0.26484549, 0.16049293]]))

**Métodos/atributos frecuentes de `ndarray`:**
- `.shape` (tupla de dimensiones), `.ndim` (nº dimensiones), `.dtype` (tipo)
- `.reshape()`, `.ravel()`, `.T` (traspuesta)
- `.sum()`, `.mean()`, `.min()`, `.max()`, `.std()`, `.var()`
- **Indexación y slicing**: `arr[0]`, `arr[1:3]`, `mat[0,1]`, `mat[:, 0]`

### Mini‑ejercicio 10
- Construí un vector `v = [5,10,15,20,25]` y devolvé su promedio y std.
- Tomá `w = np.arange(1,11)` y quedate con los múltiplos de 3.

In [21]:
# Tu solución acá

v = np.array([5,10,15,20,25])
v.mean(), v.std()

w = np.arange(1, 11)
print(w)
w[w % 3 == 0]

[ 1  2  3  4  5  6  7  8  9 10]


array([3, 6, 9])

---
## 11) Pandas: métodos y atributos útiles en DataFrames

Recordatorio: un **DataFrame** es una **tabla** (filas x columnas). Cada columna es una **Serie**.

Desde la sección anterior ya tenemos `df`. Veamos métodos y atributos útiles:

In [7]:
# Si no existe df, recrearlo (por si se ejecuta esta celda primero)
try:
    df
except NameError:
    import pandas as pd
    data = {
        "Asegurado": ["Juan", "Ana", "Pedro", "Laura"],
        "Edad": [34, 45, 29, 52],
        "Prima": [1200, 1500, 950, 2000],
        "Suma_Asegurada": [100000, 120000, 80000, 150000],
    }
    df = pd.DataFrame(data)

df.head(), df.shape, df.columns, df.dtypes

(  Asegurado  Edad  Prima  Suma_Asegurada
 0      Juan    34   1200          100000
 1       Ana    45   1500          120000
 2     Pedro    29    950           80000
 3     Laura    52   2000          150000,
 (4, 4),
 Index(['Asegurado', 'Edad', 'Prima', 'Suma_Asegurada'], dtype='object'),
 Asegurado         object
 Edad               int64
 Prima              int64
 Suma_Asegurada     int64
 dtype: object)

In [8]:
# Estadísticos y conteos
(
    df.count(),    # cantidad de no nulos por columna
    df.sum(numeric_only=True),
    df.min(numeric_only=True),
    df.max(numeric_only=True),
    df.mean(numeric_only=True),
    df.median(numeric_only=True),
    df.std(numeric_only=True),
)

(Asegurado         4
 Edad              4
 Prima             4
 Suma_Asegurada    4
 dtype: int64,
 Edad                 160
 Prima               5650
 Suma_Asegurada    450000
 dtype: int64,
 Edad                 29
 Prima               950
 Suma_Asegurada    80000
 dtype: int64,
 Edad                  52
 Prima               2000
 Suma_Asegurada    150000
 dtype: int64,
 Edad                  40.0
 Prima               1412.5
 Suma_Asegurada    112500.0
 dtype: float64,
 Edad                  39.5
 Prima               1350.0
 Suma_Asegurada    110000.0
 dtype: float64,
 Edad                 10.424331
 Prima               451.617463
 Suma_Asegurada    29860.788112
 dtype: float64)

In [9]:
# Selección / filtrado / ordenamiento
subset = df[["Asegurado","Prima"]]
filtrado = df[df["Prima"] > 1000]
ordenado = df.sort_values("Prima", ascending=False)
subset, filtrado, ordenado.head(3)

(  Asegurado  Prima
 0      Juan   1200
 1       Ana   1500
 2     Pedro    950
 3     Laura   2000,
   Asegurado  Edad  Prima  Suma_Asegurada
 0      Juan    34   1200          100000
 1       Ana    45   1500          120000
 3     Laura    52   2000          150000,
   Asegurado  Edad  Prima  Suma_Asegurada
 3     Laura    52   2000          150000
 1       Ana    45   1500          120000
 0      Juan    34   1200          100000)

**Listado breve de cosas posibles (DataFrame/Series):**
- **Estructura**: `.head()`, `.tail()`, `.shape`, `.columns`, `.dtypes`, `.info()`
- **Estadísticos**: `.count()`, `.sum()`, `.min()`, `.max()`, `.mean()`, `.median()`, `.std()`, `.describe()`
- **Selección**: `df[cols]`, `.loc[fila, col]`, `.iloc[idx]`
- **Filtrado**: `df[df[col] > x]`, combinaciones con `&`, `|`, `~`
- **Ordenar**: `.sort_values(col)`, `.sort_index()`
- **Crear/Modificar**: `df["nueva"] = ...`, `.assign(...)`, `.drop(columns=[...])`
- **Agrupar**: `.groupby(col).agg({...})`
- **Unir/merge**: `.merge()`, `.concat()`
- **Lectura/Escritura**: `pd.read_csv`, `to_csv`, `read_excel`, `to_excel`

### Mini‑ejercicio 11
- Calculá la **prima promedio** por `Asegurado` con `groupby`.
- Creá una columna `Prima_USD` asumiendo tipo de cambio `= 1000`.

In [10]:
# Tu solución acá

prom_por_aseg = df.groupby("Asegurado")["Prima"].mean()
df = df.assign(Prima_USD = df["Prima"] / 1000)
prom_por_aseg, df.head()

(Asegurado
 Ana      1500.0
 Juan     1200.0
 Laura    2000.0
 Pedro     950.0
 Name: Prima, dtype: float64,
   Asegurado  Edad  Prima  Suma_Asegurada  Prima_USD
 0      Juan    34   1200          100000       1.20
 1       Ana    45   1500          120000       1.50
 2     Pedro    29    950           80000       0.95
 3     Laura    52   2000          150000       2.00)