# Computación Científica Actuarial — Clase 1 (Práctica)
**Introducción a Python: entorno, variables, tipos y estructuras básicas**

> Este notebook acompaña el PPT de la clase. Ejecutá cada celda (Shift+Enter) y resolvé los mini‑ejercicios intercalados.


## 0) Preparación rápida
- Este es un **notebook (.ipynb)**: podés mezclar texto y código.
- Si estás en VS Code/Jupyter/Colab, elegí un *kernel* de Python 3.x.
- Recordá que en Python **las celdas se ejecutan en orden**.

---
## 1) Python como calculadora


In [1]:
# Operaciones aritméticas básicas
3 + 5, 10 - 4, 6 * 7, 22 / 7, 22 // 7, 22 % 7, 2 ** 10

(8, 6, 42, 3.142857142857143, 3, 1, 1024)

### Mini‑ejercicio 1
- Calculá el **perímetro** y el **área** de un rectángulo de base `12` y altura `8`.
- Mostrá los resultados.

In [ ]:
# Tu solución acá
base = 12
altura = 8
perimetro = 2 * (base + altura)
area = base * altura
print(perimetro)
print(area)

48
128


---
## 2) Variables y tipos básicos


In [55]:
edad = 34          # int (entero)
tasa = 0.035       # float (decimal)
nombre = "Ana"     # str (cadena de texto)
activo = True      # bool (booleano)
type(edad), type(tasa), type(nombre), type(activo)

(int, float, str, bool)

### Mini‑ejercicio 2
Usá un **f‑string** para imprimir algo como: `Hola Ana, tu edad es 34 y estado=Activo`.

In [56]:
# Tu solución acá
print(f"Hola {nombre}, tu edad es {edad} y estado={'Activo' if activo else 'Inactivo'}")

Hola Ana, tu edad es 34 y estado=Activo


---
## 3) Casting y operadores


In [61]:
# Casting (conversión de tipos)
x = "42"
# x + 8
int(x) + 8

50

In [62]:
# Operadores de comparación y lógicos
a, b = 10, 20
(a < b, a == b, a != b)
variable = a != b
variable

True

### Mini‑ejercicio 3
Ingresá un número (hardcodealo) y verificá si es **par**.

In [65]:
# Tu solución acá
n = 17  # cambiá este valor
es_par = (n % 2 == 0)
f"¿{n} es par? {es_par}"

'¿17 es par? False'

---
## 4) Strings y f-strings


In [67]:
s = "Actuaria y Python"
s.lower(), s.upper(), s.replace("Python", "Datos"), len(s)

# r = "Actuaria y Datos"
# len(r)
s = s.replace("Python", "Datos")
s
# len(s)

'Actuaria y Datos'

In [69]:
nombre = "Fiore"
saldo = 300000
f"Hola {nombre}, tu saldo es {saldo:.2f}"

'Hola Fiore, tu saldo es 300000.00'

### Mini‑ejercicio 4
Dado `cliente = 'maria lopez'`, transformalo en `Maria Lopez`.

In [10]:
# Tu solución acá
cliente = "maria lopez"
cliente = " ".join([p.capitalize() for p in cliente.split()])
cliente

'Maria Lopez'

---
## 5) Estructuras nativas: list, tuple, dict, set


In [70]:
# List (lista): ordenada, mutable, permite duplicados.
primas = [1200, 1500, 950, 2000]
primas[0], primas[-1], primas[1:3]  # indexación y slicing

(1200, 2000, [1500, 950])

In [71]:
# Operaciones básicas en listas
primas.append(1750)
primas.sort()
primas

[950, 1200, 1500, 1750, 2000]

In [13]:
# Tuple (tupla): ordenada, **inmutable**
periodo = ("2025-01", "2025-02", "2025-03")
periodo[0], len(periodo)

('2025-01', 3)

In [72]:
# Dict (diccionario): pares clave -> valor
poliza = {"asegurado": "Juan", "edad": 45, "prima": 1500}
poliza["asegurado"], poliza.get("prima"), list(poliza.keys()), list(poliza.values())
print(poliza)

{'asegurado': 'Juan', 'edad': 45, 'prima': 1500}


In [15]:
# Set (conjunto): colección sin duplicados
riesgos = {"vida", "retiro", "vida", "salud"}
riesgos, ("vida" in riesgos)

({'retiro', 'salud', 'vida'}, True)

### Mini‑ejercicios 5.x
1. Crear una lista de **sumas aseguradas** y calcular el **promedio**.
2. Agregar a `poliza` una clave `suma_asegurada`.
3. Usar un `set` para quitar duplicados de `clientes = ['Ana','Ana','Juan','Pedro','Juan']`.

In [74]:
# Tu solución acá
sumas = [100000, 120000, 80000, 150000]
promedio = sum(sumas) / len(sumas)
poliza["suma_asegurada"] = promedio
clientes = ['Ana','Ana','Ana','Juan','Pedro','Juan']
clientes_unicos = set(clientes)
promedio, poliza, clientes_unicos

(112500.0,
 {'asegurado': 'Juan', 'edad': 45, 'prima': 1500, 'suma_asegurada': 112500.0},
 {'Ana', 'Juan', 'Pedro'})

---
## 6) ¿Qué es un DataFrame? (pandas)


In [79]:
import pandas as pd
data = {
    "Asegurado": ["Juan", "Ana", "Pedro", "Laura"],
    "Edad": [34, 45, 29, 52],
    "Prima": [1200, 1500, 950, 2000],
    "Suma_Asegurada": [100000, 120000, 80000, 150000],
}
df = pd.DataFrame(data)
df.head()

Asegurado  Edad  Prima  Suma_Asegurada
0      Juan    34   1200          100000
1       Ana    45   1500          120000
2     Pedro    29    950           80000
3     Laura    52   2000          150000

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   Asegurado       4 non-null      object
 1   Edad            4 non-null      int64 
 2   Prima           4 non-null      int64 
 3   Suma_Asegurada  4 non-null      int64 
dtypes: int64(3), object(1)
memory usage: 260.0+ bytes


In [19]:
df.describe()

Edad        Prima  Suma_Asegurada
count   4.000000     4.000000        4.000000
mean   40.000000  1412.500000   112500.000000
std    10.424331   451.617463    29860.788112
min    29.000000   950.000000    80000.000000
25%    32.750000  1137.500000    95000.000000
50%    39.500000  1350.000000   110000.000000
75%    46.750000  1625.000000   127500.000000
max    52.000000  2000.000000   150000.000000

### Mini‑ejercicio 6
Calculá el **promedio** de la columna `Prima` y mostralo con 2 decimales.

In [20]:
# Tu solución acá
prom_prima = df["Prima"].mean()
f"Prima promedio: {prom_prima:.2f}"

'Prima promedio: 1412.50'

---
## 7) Práctica sugerida
- Repetí los mini‑ejercicios con datos distintos.
- Creá una lista de pólizas (como dicts) y calculá la prima promedio.


---
## 8) Funciones: definición, parámetros y retorno

Una **función** es un bloque de código reutilizable que recibe **parámetros** (opcionales), 
ejecuta instrucciones y **devuelve** (o no) un resultado con `return`.

**Ventajas**: evita repetir código, hace el programa más legible y testeable.

> Nota: una **librería** es un *conjunto de funciones y clases* listas para usar. 
Cuando escribimos `import math`, estamos trayendo **funciones** (p.ej. `math.sqrt`) y **constantes** (`math.pi`).

In [21]:
def saludo(nombre):
    """Devuelve un saludo personalizado.
    Args:
        nombre (str): nombre de la persona
    Returns:
        str: mensaje de saludo
    """
    return f"Hola {nombre}, ¡bienvenido a Python!"

saludo("Ana")

'Hola Ana, ¡bienvenido a Python!'

In [22]:
# Parámetros con valor por defecto y múltiples retornos

def resumen_prestamos(capital, tasa_anual=0.12, plazo_meses=12):
    tasa_mensual = tasa_anual/12
    interes_estimado = capital * tasa_mensual * plazo_meses
    total = capital + interes_estimado
    return tasa_mensual, interes_estimado, total

resumen_prestamos(100_000, plazo_meses=6)

(0.01, 6000.0, 106000.0)

### Mini‑ejercicio 8
- Escribí una función `es_par(n)` que devuelva `True`/`False`.
- Escribí otra función `mayor(a, b)` que devuelva el mayor de dos números.

In [23]:
# Tu solución acá

def es_par(n):
    return (n % 2) == 0


def mayor(a, b):
    return a if a >= b else b

es_par(14), mayor(10, 25)

(True, 25)

---
## 9) Clases, atributos y métodos (POO)

La **Programación Orientada a Objetos (POO)** organiza el código en **clases** (moldes) y **objetos** (instancias).
- **Atributos**: datos que describen al objeto (estado).
- **Métodos**: funciones definidas dentro de la clase que describen comportamientos.

`__init__` es el **constructor**: se ejecuta al crear el objeto y sirve para inicializar atributos.

In [24]:
class Auto:
    flota_total = 0  # atributo de clase (compartido)

    def __init__(self, color, marca, anio):
        self.color = color     # atributo de instancia
        self.marca = marca     # atributo de instancia
        self.anio = anio       # atributo de instancia
        Auto.flota_total += 1

    def descripcion(self):     # método de instancia
        return f"{self.marca} {self.color} ({self.anio})"

    def arrancar(self):
        return f"{self.descripcion()} está arrancando"

    @classmethod
    def cantidad_en_flota(cls):
        return cls.flota_total

    @staticmethod
    def es_antiguo(anio):
        return anio < 2000

mi_auto = Auto("rojo", "Toyota", 2020)
otro_auto = Auto("azul", "Ford", 2015)

mi_auto.arrancar(), Auto.cantidad_en_flota(), Auto.es_antiguo(1999)

('Toyota rojo (2020) está arrancando', 2, True)

**Notas**:
- `atributo de clase`: pertenece a la clase y lo comparten todas las instancias.
- `atributo de instancia`: propio de cada objeto.
- `@classmethod`: método que recibe `cls` (la clase) en vez de `self`.
- `@staticmethod`: método utilitario que no depende de `self` ni `cls`.

### Mini‑ejercicio 9
- Creá una clase `Poliza` con atributos `asegurado`, `edad`, `prima`.
- Agregá un método `resumen()` que devuelva un string con los datos.
- Probalo creando dos instancias.

In [25]:
# Tu solución acá

class Poliza:
    def __init__(self, asegurado, edad, prima):
        self.asegurado = asegurado
        self.edad = edad
        self.prima = prima
    def resumen(self):
        return f"Poliza de {self.asegurado} | edad={self.edad} | prima={self.prima}"

p1 = Poliza("Juan", 45, 1500)
p2 = Poliza("Ana", 38, 1200)

p1.resumen(), p2.resumen()

('Poliza de Juan | edad=45 | prima=1500',
 'Poliza de Ana | edad=38 | prima=1200')

---
## 10) NumPy: arrays y operaciones vectorizadas

**NumPy** provee `ndarray`, una estructura eficiente para computación numérica vectorizada.

**Creación básica:**

In [26]:
import numpy as np

arr = np.array([10, 20, 30, 40])
mat = np.array([[1,2,3],[4,5,6]])
arr, mat, arr.dtype, arr.shape, mat.shape

(array([10, 20, 30, 40]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 dtype('int64'),
 (4,),
 (2, 3))

**Operaciones vectorizadas y estadísticas rápidas:**

In [27]:
arr + 5, arr * 2, arr ** 2, arr.mean(), arr.sum(), arr.min(), arr.max(), arr.std()

(array([15, 25, 35, 45]),
 array([20, 40, 60, 80]),
 array([ 100,  400,  900, 1600]),
 np.float64(25.0),
 np.int64(100),
 np.int64(10),
 np.int64(40),
 np.float64(11.180339887498949))

**Creación útil:** `arange`, `linspace`, ceros/unos aleatorios

In [28]:
np.arange(0, 10, 2), np.linspace(0, 1, 5), np.zeros((2,3)), np.ones((2,3)), np.random.rand(2,3)

(array([0, 2, 4, 6, 8]),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]),
 array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[0.47310931, 0.21685435, 0.3242664 ],
        [0.38582975, 0.28848184, 0.43727354]]))

**Métodos/atributos frecuentes de `ndarray`:**
- `.shape` (tupla de dimensiones), `.ndim` (nº dimensiones), `.dtype` (tipo)
- `.reshape()`, `.ravel()`, `.T` (traspuesta)
- `.sum()`, `.mean()`, `.min()`, `.max()`, `.std()`, `.var()`
- **Indexación y slicing**: `arr[0]`, `arr[1:3]`, `mat[0,1]`, `mat[:, 0]`

### Mini‑ejercicio 10
- Construí un vector `v = [5,10,15,20,25]` y devolvé su promedio y std.
- Tomá `w = np.arange(1,11)` y quedate con los múltiplos de 3.

In [29]:
# Tu solución acá

v = np.array([5,10,15,20,25])
v.mean(), v.std()

w = np.arange(1, 11)
w[w % 3 == 0]

array([3, 6, 9])

---
## 11) Pandas: métodos y atributos útiles en DataFrames

Recordatorio: un **DataFrame** es una **tabla** (filas x columnas). Cada columna es una **Serie**.

Desde la sección anterior ya tenemos `df`. Veamos métodos y atributos útiles:

In [30]:
# Si no existe df, recrearlo (por si se ejecuta esta celda primero)
try:
    df
except NameError:
    import pandas as pd
    data = {
        "Asegurado": ["Juan", "Ana", "Pedro", "Laura"],
        "Edad": [34, 45, 29, 52],
        "Prima": [1200, 1500, 950, 2000],
        "Suma_Asegurada": [100000, 120000, 80000, 150000],
    }
    df = pd.DataFrame(data)

df.head(), df.shape, df.columns, df.dtypes

(  Asegurado  Edad  Prima  Suma_Asegurada
 0      Juan    34   1200          100000
 1       Ana    45   1500          120000
 2     Pedro    29    950           80000
 3     Laura    52   2000          150000,
 (4, 4),
 Index(['Asegurado', 'Edad', 'Prima', 'Suma_Asegurada'], dtype='object'),
 Asegurado         object
 Edad               int64
 Prima              int64
 Suma_Asegurada     int64
 dtype: object)

In [31]:
# Estadísticos y conteos
(
    df.count(),    # cantidad de no nulos por columna
    df.sum(numeric_only=True),
    df.min(numeric_only=True),
    df.max(numeric_only=True),
    df.mean(numeric_only=True),
    df.median(numeric_only=True),
    df.std(numeric_only=True),
)

(Asegurado         4
 Edad              4
 Prima             4
 Suma_Asegurada    4
 dtype: int64,
 Edad                 160
 Prima               5650
 Suma_Asegurada    450000
 dtype: int64,
 Edad                 29
 Prima               950
 Suma_Asegurada    80000
 dtype: int64,
 Edad                  52
 Prima               2000
 Suma_Asegurada    150000
 dtype: int64,
 Edad                  40.0
 Prima               1412.5
 Suma_Asegurada    112500.0
 dtype: float64,
 Edad                  39.5
 Prima               1350.0
 Suma_Asegurada    110000.0
 dtype: float64,
 Edad                 10.424331
 Prima               451.617463
 Suma_Asegurada    29860.788112
 dtype: float64)

In [32]:
# Selección / filtrado / ordenamiento
subset = df[["Asegurado","Prima"]]
filtrado = df[df["Prima"] > 1000]
ordenado = df.sort_values("Prima", ascending=False)
subset, filtrado, ordenado.head(3)

(  Asegurado  Prima
 0      Juan   1200
 1       Ana   1500
 2     Pedro    950
 3     Laura   2000,
   Asegurado  Edad  Prima  Suma_Asegurada
 0      Juan    34   1200          100000
 1       Ana    45   1500          120000
 3     Laura    52   2000          150000,
   Asegurado  Edad  Prima  Suma_Asegurada
 3     Laura    52   2000          150000
 1       Ana    45   1500          120000
 0      Juan    34   1200          100000)

**Listado breve de cosas posibles (DataFrame/Series):**
- **Estructura**: `.head()`, `.tail()`, `.shape`, `.columns`, `.dtypes`, `.info()`
- **Estadísticos**: `.count()`, `.sum()`, `.min()`, `.max()`, `.mean()`, `.median()`, `.std()`, `.describe()`
- **Selección**: `df[cols]`, `.loc[fila, col]`, `.iloc[idx]`
- **Filtrado**: `df[df[col] > x]`, combinaciones con `&`, `|`, `~`
- **Ordenar**: `.sort_values(col)`, `.sort_index()`
- **Crear/Modificar**: `df["nueva"] = ...`, `.assign(...)`, `.drop(columns=[...])`
- **Agrupar**: `.groupby(col).agg({...})`
- **Unir/merge**: `.merge()`, `.concat()`
- **Lectura/Escritura**: `pd.read_csv`, `to_csv`, `read_excel`, `to_excel`

### Mini‑ejercicio 11
- Calculá la **prima promedio** por `Asegurado` con `groupby`.
- Creá una columna `Prima_USD` asumiendo tipo de cambio `= 1000`.

In [33]:
# Tu solución acá

prom_por_aseg = df.groupby("Asegurado")["Prima"].mean()
df = df.assign(Prima_USD = df["Prima"] / 1000)
prom_por_aseg, df.head()

(Asegurado
 Ana      1500.0
 Juan     1200.0
 Laura    2000.0
 Pedro     950.0
 Name: Prima, dtype: float64,
   Asegurado  Edad  Prima  Suma_Asegurada  Prima_USD
 0      Juan    34   1200          100000       1.20
 1       Ana    45   1500          120000       1.50
 2     Pedro    29    950           80000       0.95
 3     Laura    52   2000          150000       2.00)